/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EnumTestEntity {
    'testEnum'?: EnumTestEntity.TestEnumEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "testEnum",
            "baseName": "testEnum",
            "type": "EnumTestEntity.TestEnumEnum"
        }    ];

    static getAttributeTypeMap() {
        return EnumTestEntity.attributeTypeMap;
    }
}

export namespace EnumTestEntity {
    export enum TestEnumEnum {
        _1em = <any> '-1em',
        _095em = <any> '-0.95em',
        _1em2 = <any> '1em',
        _095em2 = <any> '0.95em'
    }
}
