/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { FacetValue } from './facetValue';

export class Facet {
    'facetCriteria'?: string;
    'facetValues'?: Array<FacetValue>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "facetCriteria",
            "baseName": "facetCriteria",
            "type": "string"
        },
        {
            "name": "facetValues",
            "baseName": "facetValues",
            "type": "Array<FacetValue>"
        }    ];

    static getAttributeTypeMap() {
        return Facet.attributeTypeMap;
    }
}

