/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Test Component to test the generation of getValue method on Entities when one or multiple JSON Maps are present.
*/
export class JSONMapAttributeTestEntity {
    'description'?: string;
    'name'?: string;
    'properties1'?: { [key: string]: object; };
    'properties2'?: { [key: string]: object; };

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "properties1",
            "baseName": "properties1",
            "type": "{ [key: string]: object; }"
        },
        {
            "name": "properties2",
            "baseName": "properties2",
            "type": "{ [key: string]: object; }"
        }    ];

    static getAttributeTypeMap() {
        return JSONMapAttributeTestEntity.attributeTypeMap;
    }
}

