/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* Test Component to test the REST Builder support for nested array items
*/
export class NestedArrayItemsTestEntity {
    'name'?: string;
    'values'?: Array<Array<string>>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "Array<Array<string>>"
        }    ];

    static getAttributeTypeMap() {
        return NestedArrayItemsTestEntity.attributeTypeMap;
    }
}

