/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NestedTestEntity } from './nestedTestEntity';

/**
* https://www.schema.org/Document
*/
export class TestEntity {
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'description'?: string;
    'documentId'?: number;
    'id'?: number;
    'jsonProperty'?: string;
    'name'?: string;
    'nestedTestEntity'?: NestedTestEntity;
    'self'?: string;
    'testEntities'?: TestEntity;
    'type'?: TestEntity.TypeEnum;

    static discriminator: string | undefined = "type";

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date"
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "documentId",
            "baseName": "documentId",
            "type": "number"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "jsonProperty",
            "baseName": "jsonProperty",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "nestedTestEntity",
            "baseName": "nestedTestEntity",
            "type": "NestedTestEntity"
        },
        {
            "name": "self",
            "baseName": "self",
            "type": "string"
        },
        {
            "name": "testEntities",
            "baseName": "testEntities",
            "type": "TestEntity"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "TestEntity.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return TestEntity.attributeTypeMap;
    }
}

export namespace TestEntity {
    export enum TypeEnum {
        ChildTestEntity1 = <any> 'ChildTestEntity1',
        ChildTestEntity2 = <any> 'ChildTestEntity2',
        ChildTestEntity3 = <any> 'ChildTestEntity3'
    }
}
