##
## Modules
##

modules.includes.required.test.batch.class.names.includes[modules-integration-*-jdk8][relevant]=\
    **/src/testIntegration/**/staging/**/*Test.java

##
## Test Batch
##

#
# Relevant
#

    test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
        (testray.component.names == "Wiki") AND \
        (testray.main.component.name == "Upgrades Content Management") OR \
        (testray.main.component.name ~ "Export/Import") OR \
        (testray.main.component.name ~ "Site Templates") OR \
        (testray.main.component.name ~ "Staging")

    test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
        (testray.component.names == "Wiki") AND \
        (testray.main.component.name == "Upgrades Content Management") OR \
        (testray.main.component.name ~ "Upgrades Staging")

##
## Testray
##

    testray.main.component.name=Wiki