/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { TestEntity } from './testEntity';

/**
* https://www.schema.org/Folder
*/
export class NestedTestEntity {
    'dateCreated'?: Date;
    'dateModified'?: Date;
    'description'?: string;
    'id'?: number;
    'name'?: string;
    'testEntity'?: TestEntity;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dateCreated",
            "baseName": "dateCreated",
            "type": "Date"
        },
        {
            "name": "dateModified",
            "baseName": "dateModified",
            "type": "Date"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "testEntity",
            "baseName": "testEntity",
            "type": "TestEntity"
        }    ];

    static getAttributeTypeMap() {
        return NestedTestEntity.attributeTypeMap;
    }
}

