##
## Modules
##

modules.includes.required.test.batch.class.names.includes=\
    **/asset-categories-test/**/*Test.java,\
    **/src/testIntegration/**/staging/**/*Test.java

##
## Test Batch
##

#
# Relevant
#

test.batch.run.property.query[functional-tomcat*-mysql*-jdk8][relevant]=\
    (testray.main.component.name ~ "Export/Import") OR \
        (testray.main.component.name ~ "Site Templates") OR \
        (testray.main.component.name ~ "Staging")

test.batch.run.property.query[functional-upgrade*-tomcat*-mysql*-jdk8][relevant]=\
    (testray.main.component.name ~ "Upgrades Staging")

##
## Testray
##

testray.main.component.name=Categories