modified.files.includes[relevant][launch-web-playwright-rule]=**

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][launch-web-playwright-rule]=\
    launch-web.main

relevant.rule.names=launch-web-playwright-rule

test.batch.names[relevant][launch-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163

testray.main.component.name=Launches